# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: e:/EDABK/labs/lab_2/lab_2.srcs/sources_1/bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
# IP: The module: 'system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_40/bd_44e3_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_41/bd_44e3_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_42/bd_44e3_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_43/bd_44e3_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_44/bd_44e3_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_45/bd_44e3_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_46/bd_44e3_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_47/bd_44e3_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_48/bd_44e3_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_49/bd_44e3_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_50/bd_44e3_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_51/bd_44e3_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_52/bd_44e3_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_53/bd_44e3_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_54/bd_44e3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_55/bd_44e3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_56/bd_44e3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_57/bd_44e3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_58/bd_44e3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_59/bd_44e3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_60/bd_44e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_61/bd_44e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_62/bd_44e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_63/bd_44e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_64/bd_44e3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_65/bd_44e3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_66/bd_44e3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_67/bd_44e3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_68/bd_44e3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_69/bd_44e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_70/bd_44e3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_71/bd_44e3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_72/bd_44e3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_73/bd_44e3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_74/bd_44e3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_75/bd_44e3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_76/bd_44e3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_arinsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_40/bd_44e3_rinsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_41/bd_44e3_awinsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_42/bd_44e3_winsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_43/bd_44e3_binsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_44/bd_44e3_aroutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_45/bd_44e3_routsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_46/bd_44e3_awoutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_47/bd_44e3_woutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_48/bd_44e3_boutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_49/bd_44e3_arni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_50/bd_44e3_rni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_51/bd_44e3_awni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_52/bd_44e3_wni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_53/bd_44e3_bni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_57/bd_44e3_s00a2s_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_58/bd_44e3_sarn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_59/bd_44e3_srn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_60/bd_44e3_sawn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_61/bd_44e3_swn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_62/bd_44e3_sbn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_63/bd_44e3_m00s2a_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_64/bd_44e3_m00arn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_65/bd_44e3_m00rn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_66/bd_44e3_m00awn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_67/bd_44e3_m00wn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_68/bd_44e3_m00bn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_70/bd_44e3_m01s2a_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_71/bd_44e3_m01arn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_72/bd_44e3_m01rn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_73/bd_44e3_m01awn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_74/bd_44e3_m01wn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_75/bd_44e3_m01bn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: e:/EDABK/labs/lab_2/lab_2.srcs/sources_1/bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
# IP: The module: 'system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_20/bd_44e3_one_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_psr_aclk_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_arinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_40/bd_44e3_rinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_41/bd_44e3_awinsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_42/bd_44e3_winsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_43/bd_44e3_binsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_44/bd_44e3_aroutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_45/bd_44e3_routsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_46/bd_44e3_awoutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_47/bd_44e3_woutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_48/bd_44e3_boutsw_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_49/bd_44e3_arni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_50/bd_44e3_rni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_51/bd_44e3_awni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_52/bd_44e3_wni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_53/bd_44e3_bni_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_54/bd_44e3_s00mmu_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_55/bd_44e3_s00tr_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_56/bd_44e3_s00sic_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_57/bd_44e3_s00a2s_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_58/bd_44e3_sarn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_59/bd_44e3_srn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_60/bd_44e3_sawn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_61/bd_44e3_swn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_62/bd_44e3_sbn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_63/bd_44e3_m00s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_64/bd_44e3_m00arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_65/bd_44e3_m00rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_66/bd_44e3_m00awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_67/bd_44e3_m00wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_68/bd_44e3_m00bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_69/bd_44e3_m00e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_70/bd_44e3_m01s2a_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_71/bd_44e3_m01arn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_72/bd_44e3_m01rn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_73/bd_44e3_m01awn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_74/bd_44e3_m01wn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_75/bd_44e3_m01bn_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_76/bd_44e3_m01e_0.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_psr_aclk_0_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_psr_aclk_0.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_arinsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_40/bd_44e3_rinsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_41/bd_44e3_awinsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_42/bd_44e3_winsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_43/bd_44e3_binsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_44/bd_44e3_aroutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_45/bd_44e3_routsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_46/bd_44e3_awoutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_47/bd_44e3_woutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_48/bd_44e3_boutsw_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_49/bd_44e3_arni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_50/bd_44e3_rni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_51/bd_44e3_awni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_52/bd_44e3_wni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_53/bd_44e3_bni_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_57/bd_44e3_s00a2s_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_58/bd_44e3_sarn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_59/bd_44e3_srn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_60/bd_44e3_sawn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_61/bd_44e3_swn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_62/bd_44e3_sbn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_63/bd_44e3_m00s2a_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_64/bd_44e3_m00arn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_65/bd_44e3_m00rn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_66/bd_44e3_m00awn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_67/bd_44e3_m00wn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_68/bd_44e3_m00bn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_70/bd_44e3_m01s2a_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_71/bd_44e3_m01arn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_72/bd_44e3_m01rn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_73/bd_44e3_m01awn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_74/bd_44e3_m01wn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_75/bd_44e3_m01bn_0_ooc.xdc

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/EDABK/labs/lab_2/lab_2.gen/sources_1/bd/system/ip/system_axi_smc_0/smartconnect.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
